version: "3.8"

services:
    tts-app:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - /Users/ryantanmai/WORKSPACE/DOCKER/volumes/vits-tts/audio_output:/app/audio_output
        restart: unless-stopped
