services:
    neo4j:
        image: neo4j:5.26
        container_name: graphiti-neo4j
        ports:
            - "7474:7474" # HTTP
            - "7687:7687" # Bolt
        environment:
            - NEO4J_AUTH=neo4j/password # Đổi password khi deploy thật
            - NEO4J_PLUGINS=["apoc"]
        volumes:
            - /Users/ryantanmai/WORKSPACE/DOCKER/volumes/neo4j/data:/data
            - /Users/ryantanmai/WORKSPACE/DOCKER/volumes/neo4j/logs:/logs
            - /Users/ryantanmai/WORKSPACE/DOCKER/volumes/neo4j/import:/var/lib/neo4j/import
            - /Users/ryantanmai/WORKSPACE/DOCKER/volumes/neo4j/plugins:/plugins
        restart: unless-stopped
